[tools]
"cargo:stau" = "latest"
"github:itaysk/kubectl-neat" = "latest"
"github:ramonvermeulen/whosthere" = "latest"
"github:sinclairtarget/git-who" = "latest"
"github:vmware/govmomi" = "latest"
"npm:@cyclonedx/cdxgen" = "latest"
"pipx:black" = "latest"
age = "latest"
biome = "latest"
bob = "latest"
btop = "latest"
cyclonedx = "latest"
dagger = "latest"
delta = "latest"
eza = "latest"
fnox = "latest"
glab = "latest"
helm = "latest"
jj = "latest"
k9s = "latest"
kind = "latest"
krew = "latest"
kubectl = "latest"
kustomize = "latest"
lazygit = "latest"
node = "24"
opentofu = "latest"
python = "latest"
shellcheck = "latest"
talosctl = "latest"
terraform = "latest"
terragrunt = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
yamlfmt = "latest"
yazi = "latest"
zoxide = "latest"
