[[search_dirs]]
path = "$HOME/projects/active"
depth = 10

[[search_dirs]]
path = "$HOME/projects/admin"
depth = 10

[[search_dirs]]
path = "$HOME/.config"
depth = 10

[[search_dirs]]
path = "$HOME"
depth = 1
