[settings]
install_dir = "~/.local/bin"

[[tools]]
name = "biome"
repo = "biomejs/biome"
version = "@biomejs/biome@2.3.12"

[[tools]]
name = "btop"
repo = "aristocratos/btop"
version = "v1.4.6"

[[tools]]
name = "delta"
repo = "dandavison/delta"
version = "0.18.2"

[[tools]]
name = "eza"
repo = "eza-community/eza"
version = "v0.23.4"

[[tools]]
name = "git-who"
repo = "sinclairtarget/git-who"
version = "v1.2"

[[tools]]
name = "govc"
repo = "vmware/govmomi"
version = "v0.52.0"

[[tools]]
name = "jj"
repo = "jj-vcs/jj"
version = "v0.37.0"

[[tools]]
name = "k9s"
repo = "derailed/k9s"
version = "v0.50.18"

[[tools]]
name = "kind"
repo = "kubernetes-sigs/kind"
version = "v0.31.0"

[[tools]]
name = "krew"
repo = "kubernetes-sigs/krew"
version = "v0.4.5"

[[tools]]
name = "kubectl-neat"
repo = "itaysk/kubectl-neat"
version = "v2.0.4"

[[tools]]
name = "kustomize"
repo = "kubernetes-sigs/kustomize"
version = "kustomize/v5.8.0"

[[tools]]
name = "lazydocker"
repo = "jesseduffield/lazydocker"
version = "v0.24.4"

[[tools]]
name = "lazygit"
repo = "jesseduffield/lazygit"
version = "v0.58.1"

[[tools]]
name = "talosctl"
repo = "siderolabs/talos"
version = "v1.12.2"

[[tools]]
name = "terragrunt"
repo = "gruntwork-io/terragrunt"
version = "v0.98.0"

[[tools]]
name = "tofu"
repo = "opentofu/opentofu"
version = "v1.11.4"

[[tools]]
name = "yamlfmt"
repo = "google/yamlfmt"
version = "v0.21.0"

[[tools]]
name = "yazi"
repo = "sxyazi/yazi"
version = "v26.1.22"

[[tools]]
name = "ya"
repo = "sxyazi/yazi"
version = "v26.1.22"

[[tools]]
name = "zoxide"
repo = "ajeetdsouza/zoxide"
version = "v0.9.8"

[[tools]]
name = "bob"
repo = "MordechaiHadad/bob"
version = "v4.1.6"
