# ~/.config/yazi/yazi.toml

[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true
linemode = "size"

[preview]
tab_size = 2
max_width = 1000
max_height = 1000

[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", for = "unix" },
]

[open]
rules = [
	{ name = "*/", use = ["edit", "open"] },
	{ mime = "text/*", use = ["edit"] },
	{ mime = "image/*", use = ["open"] },
	{ mime = "video/*", use = ["open"] },
	{ mime = "audio/*", use = ["open"] },
	{ mime = "application/pdf", use = ["open"] },
	{ mime = "*", use = ["edit", "open"] },
]
